#include "avr_chipinfo_set.h"

#define LenAndRef(r) sizeof(r)/sizeof(r[0]), r
#define ChipInfo(n, i, r) {n, LenAndRef(i), LenAndRef(r)}

struct AvrChipIntInfo chip_Atmega328P_Interrupts[] = {
    {0x0000, "__RESET", "External Pin, Power-on Reset, Brown-out Reset, Watchdog Reset, and JTAG AVR Reset"},
    {0x0004, "INT0_", "External Interrupt Request 0"},
    {0x0008, "INT1_", "External Interrupt Request 1"},
    {0x000c, "PCINT0_", "Pin Change Interrupt Request 0"},
    {0x0010, "PCINT1_", "Pin Change Interrupt Request 1"},
    {0x0014, "PCINT2_", "Pin Change Interrupt Request 2"},
    {0x0018, "WDT", "Watchdog Time-out Interrupt"},
    {0x001c, "TIMER2_COMPA", "Timer/Counter2 Compare Match A"},
    {0x0020, "TIMER2_COMPB", "Timer/Counter2 Compare Match B"},
    {0x0034, "TIMER2_OVF", "Timer/Counter1 Overflow"},
    {0x0028, "TIMER1_CAPT", "Timer/Counter1 Compare Match"},
    {0x002c, "TIMER1_COMPA", "Timer/Counter1 Compare Match A"},
    {0x0030, "TIMER1_COMPB", "Timer/Counter1 Compare Match A"},
    {0x0038, "TIMER0_COMPA", "Timer/Counter0 Compare Match A"},
    {0x003c, "TIMER0_COMPB", "Timer/Counter0 Compare Match B"},
    {0x0040, "TIMER0_OVF", "Timer/Counter0 Overflow"},
    {0x0044, "SPI_STC", "Serial Transfer Complete"},
    {0x0048, "USART0_RXC", "USART Rx Complete"},
    {0x004c, "USART0_UDRE", "USART Data Register Empty"},
    {0x0050, "USART0_TXC", "USART Tx Complete"},
    {0x0054, "ADC", "ADC Conversion Complete"},
    {0x0058, "EE_READY", "EEPROM Ready"},
    {0x005c, "ANALOG_COMP", "Analog Comparator"},
    {0x0060, "TWI", "2-wire Serial Interface"},
    {0x0064, "SPM_READY", "Store Program Memory Ready"},
};

struct AvrChipIoRegInfo chip_Atmega328P_Ioregs[] = {
    {0x0003, "PINB", "Port B Input Pins Address", {
        {"PINB0", ""},
        {"PINB1", ""},
        {"PINB2", ""},
        {"PINB3", ""},
        {"PINB4", ""},
        {"PINB5", ""},
        {"PINB6", ""},
        {"PINB7", ""},
    }},
    {0x0004, "DDRB", "Port B Data Direction Register", {
        {"DDB0", "Port B Data Direction Register bit 0"},
        {"DDB1", "Port B Data Direction Register bit 1"},
        {"DDB2", "Port B Data Direction Register bit 2"},
        {"DDB3", "Port B Data Direction Register bit 3"},
        {"DDB4", "Port B Data Direction Register bit 4"},
        {"DDB5", "Port B Data Direction Register bit 5"},
        {"DDB6", "Port B Data Direction Register bit 6"},
        {"DDB7", "Port B Data Direction Register bit 7"},
    }},
    {0x0005, "PORTB", "Port B Data Register", {
        {"PORTB0", "Port B Data Register bit 0"},
        {"PORTB1", "Port B Data Register bit 1"},
        {"PORTB2", "Port B Data Register bit 2"},
        {"PORTB3", "Port B Data Register bit 3"},
        {"PORTB4", "Port B Data Register bit 4"},
        {"PORTB5", "Port B Data Register bit 5"},
        {"PORTB6", "Port B Data Register bit 6"},
        {"PORTB7", "Port B Data Register bit 7"},
    }},
    {0x0006, "PINC", "Port C Input Pins Address", {
        {"PINC0", ""},
        {"PINC1", ""},
        {"PINC2", ""},
        {"PINC3", ""},
        {"PINC4", ""},
        {"PINC5", ""},
        {"PINC6", ""},
        {"", ""},
    }},
    {0x0007, "DDRC", "Port C Data Direction Register", {
        {"DDB0", "Port C Data Direction Register bit 0"},
        {"DDB1", "Port C Data Direction Register bit 1"},
        {"DDB2", "Port C Data Direction Register bit 2"},
        {"DDB3", "Port C Data Direction Register bit 3"},
        {"DDB4", "Port C Data Direction Register bit 4"},
        {"DDB5", "Port C Data Direction Register bit 5"},
        {"DDB6", "Port C Data Direction Register bit 6"},
        {"", ""},
    }},
    {0x0008, "PORTC", "Port C Data Register", {
        {"PORTB0", "Port C Data Register bit 0"},
        {"PORTB1", "Port C Data Register bit 1"},
        {"PORTB2", "Port C Data Register bit 2"},
        {"PORTB3", "Port C Data Register bit 3"},
        {"PORTB4", "Port C Data Register bit 4"},
        {"PORTB5", "Port C Data Register bit 5"},
        {"PORTB6", "Port C Data Register bit 6"},
        {"", ""},
    }},
    {0x0009, "PIND", "Port D Input Pins Address", {
        {"PINB0", ""},
        {"PINB1", ""},
        {"PINB2", ""},
        {"PINB3", ""},
        {"PINB4", ""},
        {"PINB5", ""},
        {"PINB6", ""},
        {"PINB7", ""},
    }},
    {0x000a, "DDRD", "Port D Data Direction Register", {
        {"DDB0", "Port D Data Direction Register bit 0"},
        {"DDB1", "Port D Data Direction Register bit 1"},
        {"DDB2", "Port D Data Direction Register bit 2"},
        {"DDB3", "Port D Data Direction Register bit 3"},
        {"DDB4", "Port D Data Direction Register bit 4"},
        {"DDB5", "Port D Data Direction Register bit 5"},
        {"DDB6", "Port D Data Direction Register bit 6"},
        {"DDB7", "Port D Data Direction Register bit 7"},
    }},
    {0x000b, "PORTD", "Port D Data Register", {
        {"PORTB0", "Port D Data Register bit 0"},
        {"PORTB1", "Port D Data Register bit 1"},
        {"PORTB2", "Port D Data Register bit 2"},
        {"PORTB3", "Port D Data Register bit 3"},
        {"PORTB4", "Port D Data Register bit 4"},
        {"PORTB5", "Port D Data Register bit 5"},
        {"PORTB6", "Port D Data Register bit 6"},
        {"PORTB7", "Port D Data Register bit 7"},
    }},
    {0x0015, "TIFR0", "Timer/Counter0 Interrupt Flag Register", {
        {"TOV", "Timer/Counter0 Overflow Flag"},
        {"OCFB", "Timer/Counter0, Output Compare B Match Flag"},
        {"OCFA", "Timer/Counter0, Output Compare A Match Flag"},
        {"", ""},
        {"", ""},
        {"", ""},
        {"", ""},
        {"", ""},
    }},
    {0x0016, "TIFR1", "Timer/Counter1 Interrupt Flag Register", {
        {"TOV", "Timer/Counter1 Overflow Flag"},
        {"OCFB", "Timer/Counter1, Output Compare B Match Flag"},
        {"OCFA", "Timer/Counter1, Output Compare A Match Flag"},
        {"", ""},
        {"", ""},
        {"ICF", "Timer/Counter1, Input Capture Flag"},
        {"", ""},
        {"", ""},
    }},
    {0x0017, "TIFR2", "Timer/Counter2 Interrupt Flag Register", {
        {"TOV", "Timer/Counter2 Overflow Flag"},
        {"OCFB", "Timer/Counter2, Output Compare B Match Flag"},
        {"OCFA", "Timer/Counter2, Output Compare A Match Flag"},
        {"", ""},
        {"", ""},
        {"", ""},
        {"", ""},
        {"", ""},
    }},
    {0x001b, "PCIFR", "Pin Change Interrupt Flag Register", {
        {"PCIF0", "Pin Change Interrupt Flag 0"},
        {"PCIF1", "Pin Change Interrupt Flag 1"},
        {"PCIF2", "Pin Change Interrupt Flag 2"},
        {"", ""},
        {"", ""},
        {"", ""},
        {"", ""},
        {"", ""},
    }},
    {0x001c, "EIFR", "External Interrupt Flag Register", {
        {"INTF0", "External Interrupt Flag 0"},
        {"INTF1", "External Interrupt Flag 1"},
        {"", ""},
        {"", ""},
        {"", ""},
        {"", ""},
        {"", ""},
        {"", ""},
    }},
    {0x001d, "EIMSK", "External Interrupt Mask Register", {
        {"INT0", "External Interrupt Request 0 Enable"},
        {"INT1", "External Interrupt Request 1 Enable"},
        {"", ""},
        {"", ""},
        {"", ""},
        {"", ""},
        {"", ""},
        {"", ""},
    }},
    {0x001e, "GPIOR0", "General Purpose I/O Register 0", {
        {"", ""},
        {"", ""},
        {"", ""},
        {"", ""},
        {"", ""},
        {"", ""},
        {"", ""},
        {"", ""},
    }},
    {0x001f, "EECR", "The EEPROM Control Register", {
        {"EERE", "EEPROM Read Enable"},
        {"EEPE", "EEPROM Write Enable"},
        {"EEMPE", "EEPROM Master Write Enable"},
        {"EERIE", "EEPROM Ready Interrupt Enable"},
        {"EEPM0", "EEPROM Programming Mode Bits 0"},
        {"EEPM1", "EEPROM Programming Mode Bits 1"},
        {"", ""},
        {"", ""},
    }},
    {0x0020, "EEDR", "EEPROM Data Register", {
        {"", ""},
        {"", ""},
        {"", ""},
        {"", ""},
        {"", ""},
        {"", ""},
        {"", ""},
        {"", ""},
    }},
    {0x0021, "EEARL", "EEPROM Address Register Low Byte", {
        {"", ""},
        {"", ""},
        {"", ""},
        {"", ""},
        {"", ""},
        {"", ""},
        {"", ""},
        {"", ""},
    }},
    {0x0022, "EEARH", "The EEPROM Address Register High", {
        {"", ""},
        {"", ""},
        {"", ""},
        {"", ""},
        {"", ""},
        {"", ""},
        {"", ""},
        {"", ""},
    }},
    {0x0023, "GTCCR", "General Timer/Counter Control Register", {
        {"PSRSYNC", "PSRSYNC: Prescaler Reset"},
        {"PSRASY", "PSRASY: Prescaler Reset Timer/Counter2"},
        {"", ""},
        {"", ""},
        {"", ""},
        {"", ""},
        {"", ""},
        {"TSM", "TSM: Timer/Counter Synchronization mode"},
    }},
    {0x0024, "TCCR0A", "Timer/Counter Control Register A", {
        {"WGM00", "WGM00: Waveform Generation Mode"},
        {"WGM01", "WGM01: Waveform Generation Mode"},
        {"", ""},
        {"", ""},
        {"COM0B0", "COM0B0: Compare Match Output B Mode"},
        {"COM0B1", "COM0B1: Compare Match Output B Mode"},
        {"COM0A0", "COM0A0: Compare Match Output A Mode"},
        {"COM0A1", "COM0A1: Compare Match Output A Mode"},
    }},
    {0x0025, "TCCR0B", "Timer/Counter Control Register B", {
        {"CS00", "CS00: Clock Select"},
        {"CS01", "CS01: Clock Select"},
        {"CS02", "CS02: Clock Select"},
        {"WGM02", "WGM02: Waveform Generation Mode"},
        {"", ""},
        {"", ""},
        {"FOC0B", "FOC0B: Force Output Compare B"},
        {"FOC0A", "FOC0A: Force Output Compare A"},
    }},
    {0x0026, "TCNT0", "Timer/Counter0 (8 Bit)", {
        {"", ""},
        {"", ""},
        {"", ""},
        {"", ""},
        {"", ""},
        {"", ""},
        {"", ""},
        {"", ""},
    }},
    {0x0027, "OCR0A", "Timer/Counter0 Output Compare Register A", {
        {"", ""},
        {"", ""},
        {"", ""},
        {"", ""},
        {"", ""},
        {"", ""},
        {"", ""},
        {"", ""},
    }},
    {0x0028, "OCR0B", "Timer/Counter0 Output Compare Register B", {
        {"", ""},
        {"", ""},
        {"", ""},
        {"", ""},
        {"", ""},
        {"", ""},
        {"", ""},
        {"", ""},
    }},
    {0x002a, "GPIOR1", "General Purpose I/O Register 1", {
        {"", ""},
        {"", ""},
        {"", ""},
        {"", ""},
        {"", ""},
        {"", ""},
        {"", ""},
        {"", ""},
    }},
    {0x002b, "GPIOR2", "General Purpose I/O Register 2", {
        {"", ""},
        {"", ""},
        {"", ""},
        {"", ""},
        {"", ""},
        {"", ""},
        {"", ""},
        {"", ""},
    }},
    {0x002c, "SPCR0", "SPI Control Register", {
        {"SPR0", "SPR0: SPI Clock Rate Select 0"},
        {"SPR1", "SPR1: SPI Clock Rate Select 1"},
        {"CPHA", "CPHA: Clock Phase"},
        {"CPOL", "CPOL: Clock Polarity"},
        {"MSTR", "MSTR: Master/Slave Select"},
        {"DORD", "DORD: Data Order"},
        {"SPE", "SPE: SPI Enable"},
        {"SPIE", "SPIE: SPI Interrupt Enable"},
    }},
    {0x002d, "SPSR0", "SPI Status Register", {
        {"SPI2X", "SPI2X: Double SPI Speed Bit"},
        {"", ""},
        {"", ""},
        {"", ""},
        {"", ""},
        {"", ""},
        {"WCOL", "WCOL: Write COLlision Flag"},
        {"SPIF", "SPIF: SPI Interrupt Flag"},
    }},
    {0x002e, "SPDR0", "SPI Data Register", {
        {"", ""},
        {"", ""},
        {"", ""},
        {"", ""},
        {"", ""},
        {"", ""},
        {"", ""},
        {"", ""},
    }},
    {0x0030, "ACSR", "Analog Comparator Control and Status Register", {
        {"ACIS0", "ACIS0: Analog Comparator Interrupt Mode Select"},
        {"ACIS1", "ACIS1: Analog Comparator Interrupt Mode Select"},
        {"ACIC", "ACIC: Analog Comparator Input Capture Enable"},
        {"ACIE", "ACIE: Analog Comparator Interrupt Enable"},
        {"ACI", "ACI: Analog Comparator Interrupt Flag"},
        {"ACO", "ACO: Analog Comparator Output"},
        {"ACBG", "ACBG: Analog Comparator Bandgap Select"},
        {"ACD", "ACD: Analog Comparator Disable"},
    }},
    {0x0031, "DWDR", "debugWire Data Register", {
        {"", ""},
        {"", ""},
        {"", ""},
        {"", ""},
        {"", ""},
        {"", ""},
        {"", ""},
        {"", ""},
    }},
    {0x0033, "SMCR", "Sleep Mode Control Register", {
        {"SE", "Sleep Enable"},
        {"SM0", "Sleep Mode Select 0"},
        {"SM1", "Sleep Mode Select 1"},
        {"SM2", "Sleep Mode Select 2"},
        {"", ""},
        {"", ""},
        {"", ""},
        {"", ""},
    }},
    {0x0034, "MCUSR", "MCU Status Register", {
        {"PORF", "Power-on Reset Flag"},
        {"EXTRF", "External Reset Flag"},
        {"BORF", "Brown-out Reset Flag"},
        {"WDRF", "Watchdog Reset Flag"},
        {"", ""},
        {"", ""},
        {"", ""},
        {"", ""},
    }},
    {0x0035, "MCUCR", "MCU Control Register", {
        {"IVCE", "Interrupt Vector Change Enable"},
        {"IVSEL", "Interrupt Vector Select"},
        {"", ""},
        {"", ""},
        {"PUD", "Pull-up DIsable"},
        {"BODSE", "BOD Sleep Enable"},
        {"BODS", "BOD Sleep"},
        {"", ""},
    }},
    {0x0037, "SPMCSR", "Store Program Memory Control Register", {
        {"SPMEN", "Store Program Memory Enable"},
        {"PGERS", "Page Erase"},
        {"PGWRT", "Page Write"},
        {"BLBSET", "Boot Lock Bit Set"},
        {"RWWSRE", "Read-While-Write Section Read Enable"},
        {"SIGRD", "Signature Row Read"},
        {"RWWSB", "Read-While-Write Section Busy"},
        {"SPMIE", "SPM Interrupt Enable"},
    }},
    {0x003d, "SPL", "Stack Pointer Low", {
        {"SP0", ""},
        {"SP1", ""},
        {"SP2", ""},
        {"SP3", ""},
        {"SP4", ""},
        {"SP5", ""},
        {"SP6", ""},
        {"SP7", ""},
    }},
    {0x003e, "SPH", "Stack Pointer High", {
        {"SP8", ""},
        {"SP9", ""},
        {"SP10", ""},
        {"SP11", ""},
        {"SP12", ""},
        {"SP13", ""},
        {"SP14", ""},
        {"SP15", ""},
    }},
    {0x003f, "SREG", "Status Register", {
        {"C", "CarryFlag"},
        {"Z", "Zero Flag"},
        {"N", "Negative Flag"},
        {"V", "Two's Complement Overflow Flag"},
        {"S", "Sign Bit"},
        {"H", "Half Carry Flag"},
        {"T", "Bit Copy Storage"},
        {"I", "Global Interrupt Enable"},
    }},
    {0x0040, "WDTCSR", "Watchdog Timer Control Register", {
        {"WDP0", "WDP0: Watchdog Timer Prescaler 3"},
        {"WDP1", "WDP1: Watchdog Timer Prescaler 3"},
        {"WDP2", "WDP2: Watchdog Timer Prescaler 3"},
        {"WDE", "WDCE: Watchdog Change Enable"},
        {"WDCE", "WDCE: Watchdog Change Enable"},
        {"WDP3", "WDP3: Watchdog Timer Prescaler 3"},
        {"WDIE", "WDIE: Watchdog Interrupt Enable"},
        {"WDIF", "WDIF: Watchdog Interrupt Flag"},
    }},
    {0x0041, "CLKPR", "Clock Prescale Register", {
        {"CLKPS0", "CLKPS0 Clock Prescaler Select bit 0"},
        {"CLKPS1", "CLKPS1 Clock Prescaler Select bit 1"},
        {"CLKPS2", "CLKPS2 Clock Prescaler Select bit 2"},
        {"CLKPS3", "CLKPS3 Clock Prescaler Select bit 3"},
        {"", ""},
        {"", ""},
        {"", ""},
        {"CLKPCE", "CLKPCE: Clock Prescaler Change Enable"},
    }},
    {0x0044, "PRR", "Power Reduction Register", {
        {"PRADC", "PRADC: Power Reduction ADC"},
        {"PRUSART0", "PRUSART0: Power Reduction USART0"},
        {"PRSPI", "PRSPI: Power Reduction Serial Peripheral Interface"},
        {"PRTIM1", "PRTIM1: Power Reduction Timer/Counter1"},
        {"", ""},
        {"PRTIM0", "PRTIM0: Power Reduction Timer/Counter0"},
        {"PRTIM2", "PRTIM2: Power Reduction Timer/Counter2"},
        {"PRTWI0", "PRTWI: Power Reduction TWI"},
    }},
    {0x0046, "OSCCAL", "Oscillator Calibration Register", {
        {"", ""},
        {"", ""},
        {"", ""},
        {"", ""},
        {"", ""},
        {"", ""},
        {"", ""},
        {"", ""},
    }},
    {0x0048, "PCICR", "Pin Change Interrupt Control Register", {
        {"PCIE0", "PCIE0: Pin Change Interrupt Enable 0"},
        {"PCIE1", "PCIE1: Pin Change Interrupt Enable 1"},
        {"PCIE2", "PCIE2: Pin Change Interrupt Enable 2"},
        {"PCIE3", "PCIE3: Pin Change Interrupt Enable 3"},
        {"", ""},
        {"", ""},
        {"", ""},
        {"", ""},
    }},
    {0x0049, "EICRA", "External Interrupt Control Register A", {
        {"ISC00", "ISC00: External Interrupt Sense Control Bits"},
        {"ISC01", "ISC01: External Interrupt Sense Control Bits"},
        {"ISC10", "ISC10: External Interrupt Sense Control Bits"},
        {"ISC11", "ISC11: External Interrupt Sense Control Bits"},
        {"", ""},
        {"", ""},
        {"", ""},
        {"", ""},
    }},
    {0x004b, "PCMSK0", "Pin Change Mask Register 0", {
        {"PCINT0", "PCINT0 Pin Change Enable Mask"},
        {"PCINT1", "PCINT1 Pin Change Enable Mask"},
        {"PCINT2", "PCINT2 Pin Change Enable Mask"},
        {"PCINT3", "PCINT3 Pin Change Enable Mask"},
        {"PCINT4", "PCINT4 Pin Change Enable Mask"},
        {"PCINT5", "PCINT5 Pin Change Enable Mask"},
        {"PCINT6", "PCINT6 Pin Change Enable Mask"},
        {"PCINT7", "PCINT7 Pin Change Enable Mask"},
    }},
    {0x004c, "PCMSK1", "Pin Change Mask Register 1", {
        {"PCINT8", "PCINT8 Pin Change Enable Mask"},
        {"PCINT9", "PCINT9 Pin Change Enable Mask"},
        {"PCINT10", "PCINT10 Pin Change Enable Mask"},
        {"PCINT11", "PCINT11 Pin Change Enable Mask"},
        {"PCINT12", "PCINT12 Pin Change Enable Mask"},
        {"PCINT13", "PCINT13 Pin Change Enable Mask"},
        {"PCINT14", "PCINT14 Pin Change Enable Mask"},
        {"PCINT15", "PCINT15 Pin Change Enable Mask"},
    }},
    {0x004d, "PCMSK2", "Pin Change Mask Register 2", {
        {"PCINT16", "PCINT16 Pin Change Enable Mask"},
        {"PCINT17", "PCINT17 Pin Change Enable Mask"},
        {"PCINT18", "PCINT18 Pin Change Enable Mask"},
        {"PCINT19", "PCINT19 Pin Change Enable Mask"},
        {"PCINT20", "PCINT20 Pin Change Enable Mask"},
        {"PCINT21", "PCINT21 Pin Change Enable Mask"},
        {"PCINT22", "PCINT22 Pin Change Enable Mask"},
        {"PCINT23", "PCINT23 Pin Change Enable Mask"},
    }},
    {0x004e, "TIMSK0", "Timer/Counter Interrupt Mask Register", {
        {"TOIE0", "TOIE0: Timer/Counter0 Overflow Interrupt Enable"},
        {"OCIE0A", "OCIE0A: Timer/Counter0 Output Compare Match A Interrupt Enable"},
        {"OCIE0B", "OCIE0B: Timer/Counter Output Compare Match B Interrupt Enable"},
        {"", ""},
        {"", ""},
        {"", ""},
        {"", ""},
        {"", ""},
    }},
    {0x004f, "TIMSK1", "Timer/Counter1 Interrupt Mask Register", {
        {"TOIE1", "TOIE1: Timer/Counter1, Overflow Interrupt Enable"},
        {"OCIE1A", "OCIE1A: Timer/Counter1, Output Compare A Match Interrupt Enable"},
        {"OCIE1B", "OCIE1B: Timer/Counter1, Output Compare B Match Interrupt Enable"},
        {"", ""},
        {"", ""},
        {"ICIE1", "ICIE1: Timer/Counter1, Input Capture Interrupt Enable"},
        {"", ""},
        {"", ""},
    }},
    {0x0050, "TIMSK2", "Timer/Counter2 Interrupt Mask Register", {
        {"TOIE2", "TOIE2: Timer/Counter2 Overflow Interrupt Enable"},
        {"OCIE2A", "OCIE2A: Timer/Counter2 Output Compare Match A Interrupt Enable"},
        {"OCIE2B", "OCIE2B: Timer/Counter2 Output Compare Match B Interrupt Enable"},
        {"", ""},
        {"", ""},
        {"", ""},
        {"", ""},
        {"", ""},
    }},
    {0x0058, "ADCL", "ADC Data Register Low byte", {
        {"", ""},
        {"", ""},
        {"", ""},
        {"", ""},
        {"", ""},
        {"", ""},
        {"", ""},
        {"", ""},
    }},
    {0x0059, "ADCH", "ADC Data Register High byte", {
        {"", ""},
        {"", ""},
        {"", ""},
        {"", ""},
        {"", ""},
        {"", ""},
        {"", ""},
        {"", ""},
    }},
    {0x005a, "ADCSRA", "ADC Control and Status Register A", {
        {"ADPS0", "ADPS0 ADC Prescaler Select bit 0"},
        {"ADPS1", "ADPS1 ADC Prescaler Select bit 1"},
        {"ADPS2", "ADPS2 ADC Prescaler Select bit 2"},
        {"ADIE", "ADIE: ADC Interrupt Enable"},
        {"ADIF", "ADIF: ADC Interrupt Flag"},
        {"ADATE", "ADATE: ADC Auto Trigger Enable"},
        {"ADSC", "ADSC: ADC Start Conversion"},
        {"ADEN", "ADEN: ADC Enable"},
    }},
    {0x005b, "ADCSRB", "ADC Control and Status Register B", {
        {"ADTS0", ""},
        {"ADTS1", ""},
        {"ADTS2", ""},
        {"", ""},
        {"", ""},
        {"", ""},
        {"ACME", ""},
        {"", ""},
    }},
    {0x005c, "ADMUX", "ADC Multiplexer Selection Register", {
        {"MUX0", "MUX0 Analog Channel and Gain Selection bit 0"},
        {"MUX1", "MUX1 Analog Channel and Gain Selection bit 1"},
        {"MUX2", "MUX2 Analog Channel and Gain Selection bit 2"},
        {"MUX3", "MUX3 Analog Channel and Gain Selection bit 3"},
        {"MUX4", "MUX4 Analog Channel and Gain Selection bit 4"},
        {"ADLAR", "ADLAR: ADC Left Adjust Result"},
        {"REFS0", "REFS0 Reference Selection Bits"},
        {"REFS1", "REFS1 Reference Selection Bits"},
    }},
    {0x005e, "DIDR0", "Digital Input Disable Register 0", {
        {"ADC0D", "ADC0D: ADC0 Digital Input Disable"},
        {"ADC1D", "ADC1D: ADC1 Digital Input Disable"},
        {"ADC2D", "ADC2D: ADC2 Digital Input Disable"},
        {"ADC3D", "ADC3D: ADC3 Digital Input Disable"},
        {"ADC4D", "ADC4D: ADC4 Digital Input Disable"},
        {"ADC5D", "ADC5D: ADC5 Digital Input Disable"},
        {"ADC6D", "ADC6D: ADC6 Digital Input Disable"},
        {"ADC7D", "ADC7D: ADC7 Digital Input Disable"},
    }},
    {0x005f, "DIDR1", "Digital Input Disable Register 1", {
        {"AIN0D", "AIN0D: AIN0 Digital Input Disable"},
        {"AIN1D", "AIN1D: AIN1 Digital Input Disable"},
        {"", ""},
        {"", ""},
        {"", ""},
        {"", ""},
        {"", ""},
        {"", ""},
    }},
    {0x0060, "TCCR1A", "Timer/Counter1 Control Register A", {
        {"WGM10", "WGM10 Waveform Generation Mode"},
        {"WGM11", "WGM11 Waveform Generation Mode"},
        {"", ""},
        {"", ""},
        {"COM1B0", "COM1B0 Compare Output Mode for Channel B"},
        {"COM1B1", "COM1B1 Compare Output Mode for Channel B"},
        {"COM1A0", "COM1A0 Compare Output Mode for Channel A"},
        {"COM1A1", "COM1A1 Compare Output Mode for Channel A"},
    }},
    {0x0061, "TCCR1B", "Timer/Counter1 Control Register B", {
        {"CS10", "CS10 Clock Select"},
        {"CS11", "CS11 Clock Select"},
        {"CS12", "CS12 Clock Select"},
        {"WGM12", "WGM12 Waveform Generation Mode"},
        {"WGM13", "WGM13 Waveform Generation Mode"},
        {"", ""},
        {"ICES1", "ICES1: Input Capture Edge Select"},
        {"ICNC1", "ICNC1: Input Capture Noise Canceler"},
    }},
    {0x0062, "TCCR1C", "Timer/Counter1 Control Register C", {
        {"", ""},
        {"", ""},
        {"", ""},
        {"", ""},
        {"", ""},
        {"", ""},
        {"FOC1B", "FOC1B: Force Output Compare for Channel B"},
        {"FOC1A", "FOC1A: Force Output Compare for Channel A"},
    }},
    {0x0064, "TCNT1L", "Timer/Counter1 - Counter Register Low Byte", {
        {"", ""},
        {"", ""},
        {"", ""},
        {"", ""},
        {"", ""},
        {"", ""},
        {"", ""},
        {"", ""},
    }},
    {0x0065, "TCNT1H", "Timer/Counter1 - Counter Register High Byte", {
        {"", ""},
        {"", ""},
        {"", ""},
        {"", ""},
        {"", ""},
        {"", ""},
        {"", ""},
        {"", ""},
    }},
    {0x0066, "ICR1L", "Timer/Counter1 - Input Capture Register Low Byte", {
        {"", ""},
        {"", ""},
        {"", ""},
        {"", ""},
        {"", ""},
        {"", ""},
        {"", ""},
        {"", ""},
    }},
    {0x0067, "ICR1H", "Timer/Counter1 - Input Capture Register High Byte", {
        {"", ""},
        {"", ""},
        {"", ""},
        {"", ""},
        {"", ""},
        {"", ""},
        {"", ""},
        {"", ""},
    }},
    {0x0068, "OCR1AL", "Timer/Counter1 - Output Compare Register A Low Byte", {
        {"", ""},
        {"", ""},
        {"", ""},
        {"", ""},
        {"", ""},
        {"", ""},
        {"", ""},
        {"", ""},
    }},
    {0x0069, "OCR1AH", "Timer/Counter1 - Output Compare Register A High Byte", {
        {"", ""},
        {"", ""},
        {"", ""},
        {"", ""},
        {"", ""},
        {"", ""},
        {"", ""},
        {"", ""},
    }},
    {0x006a, "OCR1BL", "Timer/Counter1 - Output Compare Register B Low Byte", {
        {"", ""},
        {"", ""},
        {"", ""},
        {"", ""},
        {"", ""},
        {"", ""},
        {"", ""},
        {"", ""},
    }},
    {0x006b, "OCR1BH", "Timer/Counter1 - Output Compare Register B High Byte", {
        {"", ""},
        {"", ""},
        {"", ""},
        {"", ""},
        {"", ""},
        {"", ""},
        {"", ""},
        {"", ""},
    }},
    {0x0090, "TCCR2A", "Timer/Counter Control Register A", {
        {"WGM20", "WGM20 Waveform Generation Mode"},
        {"WGM21", "WGM21 Waveform Generation Mode"},
        {"", ""},
        {"", ""},
        {"COM2B0", "COM2B0 Compare Match Output B Mode"},
        {"COM2B1", "COM2B1 Compare Match Output B Mode"},
        {"COM2A0", "COM2A0 Compare Match Output A Mode"},
        {"COM2A1", "COM2A1 Compare Match Output A Mode"},
    }},
    {0x0091, "TCCR2B", "Timer/Counter Control Register B", {
        {"CS20", "CS20 Clock Select"},
        {"CS21", "CS21 Clock Select"},
        {"CS22", "CS22 Clock Select"},
        {"WGM22", "WGM22: Waveform Generation Mode"},
        {"", ""},
        {"", ""},
        {"FOC2B", "FOC2B: Force Output Compare B"},
        {"FOC2A", "FOC2A: Force Output Compare A"},
    }},
    {0x0092, "TCNT2", "Timer/Counter2 (8 Bit)", {
        {"", ""},
        {"", ""},
        {"", ""},
        {"", ""},
        {"", ""},
        {"", ""},
        {"", ""},
        {"", ""},
    }},
    {0x0093, "OCR2A", "Timer/Counter2 Output Compare Register A", {
        {"", ""},
        {"", ""},
        {"", ""},
        {"", ""},
        {"", ""},
        {"", ""},
        {"", ""},
        {"", ""},
    }},
    {0x0094, "OCR2B", "Timer/Counter2 Output Compare Register B", {
        {"", ""},
        {"", ""},
        {"", ""},
        {"", ""},
        {"", ""},
        {"", ""},
        {"", ""},
        {"", ""},
    }},
    {0x0096, "ASSR", "Asynchronous Status Register", {
        {"TCR2BUB", "TCR2BUB: Timer/Counter Control Register2 Update Busy"},
        {"TCR2AUB", "TCR2AUB: Timer/Counter Control Register2 Update Busy"},
        {"OCR2BUB", "OCR2BUB: Output Compare Register2 Update Busy"},
        {"OCR2AUB", "OCR2AUB: Output Compare Register2 Update Busy"},
        {"TCN2UB", "TCN2UB: Timer/Counter2 Update Busy"},
        {"AS2", "AS2: Asynchronous Timer/Counter2"},
        {"EXCLK", "EXCLK: Enable External Clock Input"},
        {"", ""},
    }},
    {0x0098, "TWBR", "2-wire Serial Interface Bit Rate Register", {
        {"", ""},
        {"", ""},
        {"", ""},
        {"", ""},
        {"", ""},
        {"", ""},
        {"", ""},
        {"", ""},
    }},
    {0x0099, "TWSR", "TWI Status Register", {
        {"TWPS0", "TWPS: TWI Prescaler bit 0"},
        {"TWPS1", "TWPS: TWI Prescaler bit 1"},
        {"", ""},
        {"TWS3", "TWS: TWI Status bit 0"},
        {"TWS4", "TWS: TWI Status bit 1"},
        {"TWS5", "TWS: TWI Status bit 2"},
        {"TWS6", "TWS: TWI Status bit 3"},
        {"TWS7", "TWS: TWI Status bit 4"},
    }},
    {0x009a, "TWAR", "TWI (Slave) Address Register", {
        {"TWGCE", "TWGCE: TWI General Call Recognition Enable Bit"},
        {"TWA0", "TWA: TWI (Slave) Address Register bit 0"},
        {"TWA1", "TWA: TWI (Slave) Address Register bit 1"},
        {"TWA2", "TWA: TWI (Slave) Address Register bit 2"},
        {"TWA3", "TWA: TWI (Slave) Address Register bit 3"},
        {"TWA4", "TWA: TWI (Slave) Address Register bit 4"},
        {"TWA5", "TWA: TWI (Slave) Address Register bit 5"},
        {"TWA6", "TWA: TWI (Slave) Address Register bit 6"},
    }},
    {0x009b, "TWDR", "2-wire Serial Interface Data Register", {
        {"", ""},
        {"", ""},
        {"", ""},
        {"", ""},
        {"", ""},
        {"", ""},
        {"", ""},
        {"", ""},
    }},
    {0x009c, "TWCR", "TWI Control Register", {
        {"TWIE", "TWIE: TWI Interrupt Enable"},
        {"", ""},
        {"TWEN", "TWEN: TWI Enable Bit"},
        {"TWWC", "TWWC: TWI Write Collision Flag"},
        {"TWSTO", "TWSTO: TWI STOP Condition Bit"},
        {"TWSTA", "TWSTA: TWI START Condition Bit"},
        {"TWEA", "TWEA: TWI Enable Acknowledge Bit"},
        {"TWINT", "TWINT: TWI Interrupt Flag"},
    }},
    {0x009d, "TWAMR", "TWI (Slave) Address Mask Register", {
        {"", ""},
        {"TWAM0", "TWAM: TWI Address Mask bit 0"},
        {"TWAM1", "TWAM: TWI Address Mask bit 1"},
        {"TWAM2", "TWAM: TWI Address Mask bit 2"},
        {"TWAM3", "TWAM: TWI Address Mask bit 3"},
        {"TWAM4", "TWAM: TWI Address Mask bit 4"},
        {"TWAM5", "TWAM: TWI Address Mask bit 5"},
        {"TWAM6", "TWAM: TWI Address Mask bit 6"},
    }},
    {0x00a0, "UCSR0A", "", {
        {"MPCM0", ""},
        {"U2X0", ""},
        {"UPE0", ""},
        {"DOR0", ""},
        {"FE0", ""},
        {"UDRE0", ""},
        {"TXC0", ""},
        {"RXC0", ""},
    }},
    {0x00a1, "UCSR0B", "", {
        {"TXB80", ""},
        {"RXB80", ""},
        {"UCSZ02", ""},
        {"TXEN0", ""},
        {"RXEN0", ""},
        {"UDRIE0", ""},
        {"TXCIE0", ""},
        {"RXCIE0", ""},
    }},
    {0x00a2, "UCSR0C", "", {
        {"UCPOL0", ""},
        {"UCPHA0", ""},
        {"UDORD0", ""},
        {"", ""},
        {"", ""},
        {"", ""},
        {"UMSEL00", ""},
        {"UMSEL01", ""},
    }},
    {0x00a4, "UBRR0L", "USART0 Baud Rate Register Low Byte", {
        {"", ""},
        {"", ""},
        {"", ""},
        {"", ""},
        {"", ""},
        {"", ""},
        {"", ""},
        {"", ""},
    }},
    {0x00a5, "UBRR0H", "USART0 Baud Rate Register High Byte", {
        {"", ""},
        {"", ""},
        {"", ""},
        {"", ""},
        {"", ""},
        {"", ""},
        {"", ""},
        {"", ""},
    }},
    {0x00a6, "UDR0", "USART0 I/O Data Register", {
        {"", ""},
        {"", ""},
        {"", ""},
        {"", ""},
        {"", ""},
        {"", ""},
        {"", ""},
        {"", ""},
    }},
};

struct AvrChipInfo AVR_ChipInfo_Set[] = {
    ChipInfo("ATmega328P", chip_Atmega328P_Interrupts, chip_Atmega328P_Ioregs)
};

int AVR_TOTAL_CHIPINFOS = (sizeof(AVR_ChipInfo_Set)/sizeof(AVR_ChipInfo_Set[0]));
